version: '3.3'
services:
  mongodb:
    restart: always

  straribay_back:
    command: sh -c "npm run build && npm run start"
    expose: 
      - 7777
    restart: always
    environment: 
      - NODE_ENV=production

  straribay_front:
		command: sh -c "npm run build"
    volumes:
      - ./front/src:/app/src:rw
      - ./front/public:/app/public:rw
      - /app/front/node_modules
		environment: 
			- NODE_ENV=production
			- REACT_APP_API_BASE_URL=/straribay_back

	nginx:
		image: nginx:2.19.10
		restart: always
		ports: 
			- ${GATEWAY_PORT}:80
		volumes: 
			- ./nginx.conf:/etc/nginx/nginx.conf
			- straribay_front-build:/straribay_front-build

volumes:
  straribay_front-build: