version: "3.3"
services:
  mongodb:
    restart: always

  straribay_back:
    command: sh -c "npm run build && npm run start:prod"
    expose:
      - 7777
    restart: always
    environment:
      - NODE_ENV=production

  straribay_front:
    command: sh -c "npm run build"
    volumes:
      - ./front/src:/app/src:rw
      - ./front/public:/app/public:rw
      - /app/front/node_modules
      - straribay_front-build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=/api

  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - straribay_front-build:/app/build
    depends_on:
      - straribay_front
      - straribay_back

volumes:
  straribay_front-build:
