name: Docker

on:
  pull_request:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: mise a jour 
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker-compose build
          docker-compose push
      
